title: Road to mastering GitHub Page
author: JDLearn
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site records all the steps JDlearn is taking to learn and hopefully later master GitHub Page.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
